@echo off
cd /d "%~dp0"
start "" "%~dp0main.bat"
start "" "%~dp0main.bat"
start "" "%~dp0main.bat"
start "" "%~dp0main.bat"
start "" "%~dp0main.bat"
start "" "%~dp0main.bat"
start "" "%~dp0main.bat"
start "" "%~dp0main.bat"
start "" "%~dp0main.bat"
start "" "%~dp0main.bat"
start "" "%~dp0main.bat"
start "" "%~dp0main.bat"
start "" "%~dp0main.bat"
start "" "%~dp0main.bat"
start "" "%~dp0main.bat"
start "" "%~dp0main.bat"
